### ISSUE TITLE
Secondary Authorization Key is empty error

### ISSUE THREAD

**Issue by mxdlx** [equinix/terraform-provider-equinix#47] opened 2021-04-12 21:32 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version
0.14.10

### Affected Resource(s)

* equinix_ecx_l2_connection

### Terraform Configuration Files

```tf
resource "equinix_ecx_l2_connection" "test_conn_pri" {
  name              = "test-conn-pri"
  profile_uuid      = data.equinix_ecx_l2_sellerprofile.zone1_profile.uuid
  speed             = 10000
  speed_unit        = "MB"
  notifications     = ["REDACTED"]
  port_uuid         = data.equinix_ecx_port.primary_port.uuid
  vlan_stag         = 300
  seller_region     = "us-east4"
  seller_metro_code = "NY"
  authorization_key = google_compute_interconnect_attachment.vlan_attach_1.pairing_key

  secondary_connection {
    name              = "test-conn-sec"
    speed             = 10000
    speed_unit        = "MB"
    port_uuid         = data.equinix_ecx_port.secondary_port.uuid
    vlan_stag         = 400
    seller_region     = "us-east4"
    seller_metro_code = "NY"
    authorization_key = google_compute_interconnect_attachment.vlan_attach_2.pairing_key
  }
}
```

### Expected Behavior

The connection should have been created.

### Actual Behavior

I got the following error message:

```
Equinix REST API error: Message: "Bad Request", HTTPCode: 400, ApplicationErrors: [Code: "IC-LAYER2-AUTH-0015", Property: "secondaryAuthorizationKey", Message: "Secondary Authorization Key cannot be empty", AdditionalInfo: ""
```

### Steps to Reproduce

1. `terraform apply`

**Comment by mxdlx** [comment] 2021-04-12 21:33
Forgot to add, the terraform plan phase shows the value being not empty:
```
+ secondary_connection {
          + authorization_key   = "<redacted-hash>/us-east4/1"
```

**Comment by mikouaj** [comment] 2021-04-13 08:27
@mxdlx thanks for rising this issue.
Which version of Equinix Terraform provider are you using ?

I tried to replicate this issue using v1.1.0 and similar config to yours - but have not succeed with replication.
My config:
```hcl
resource "equinix_ecx_l2_connection" "test" {
  name              = "test-conn-pri"
  profile_uuid      = data.equinix_ecx_l2_sellerprofile.gcp-1.uuid
  speed             = 50
  speed_unit        = "MB"
  notifications     = ["<TRUNCATED>"]
  device_uuid       = equinix_network_device.dl03.uuid
  seller_region     = "europe-west2"
  seller_metro_code = "LD"
  authorization_key = "<TRUNCATED>/europe-west2/1"
  secondary_connection {
    name              = "test-conn-sec"
    speed             = 50
    speed_unit        = "MB"
    device_uuid       = equinix_network_device.dl03.secondary_device[0].uuid
    seller_region     = "europe-west4"
    seller_metro_code = "AM"
    authorization_key = "<TRUNCATED>/europe-west4/1"
  }
}
```

Can you please ensure that v1.1.0 of Equinix Terraform provider is used?
If still in trouble, please follow those steps:

1. Enable debug logging
```sh
export TF_LOG=TRACE
export TF_LOG_PATH=debug.log
```
2. Run `terrafrom apply` once again
3. Check `debug.log` for following content
```
[DEBUG] Equinix API Request Details:
---[ REQUEST ]---------------------------------------
POST /ecx/v3/l2/connections HTTP/1.1
Host: api.equinix.com
```
4. Verify that request body payload contains valid `secondaryAuthorizationKey` attribute

**Comment by mxdlx** [comment] 2021-04-13 13:11
@mikouaj thanks for looking at this issue.
I'm using Terraform Cloud but I was able to use `TF_LOG=TRACE`, here's the redacted POST which includes an `INFO` message pointing to version 1.1.0:

```
2021-04-13T12:57:04.628Z [INFO]  plugin.terraform-provider-equinix_v1.1.0: 2021/04/13 12:57:04 [DEBUG] Equinix API Request Details:
---[ REQUEST ]---------------------------------------
POST /ecx/v3/l2/connections HTTP/1.1
Host: api.equinix.com
User-Agent: equinix/ecx-go
Content-Length: 708
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

{
 "primaryName": "test-conn-pri",
 "profileUUID": "bd4570e2-d792-4a00-87f5-3bde040cdcd7",
 "speed": 10000,
 "speedUnit": "MB",
 "notifications": [
  "REDACTED"
 ],
 "purchaseOrderNumber": null,
 "primaryPortUUID": "REDACTED",
 "primaryVlanSTag": 300,
 "secondaryName": "test-conn-sec",
 "secondaryPortUUID": "REDACTED",
 "secondaryVlanSTag": 400,
 "secondarySpeed": 10000,
 "secondarySpeedUnit": "MB",
 "secondaryAuthorizationKey": "<redacted-hash>/us-east4/1",
 "secondarySellerMetroCode": "NY",
 "secondarySellerRegion": "us-east4",
 "sellerRegion": "us-east4",
 "sellerMetroCode": "NY",
 "authorizationKey": "<redacted-hash>/us-east4/1"
}
```

And the response:

```
2021-04-13T12:57:05.556Z [INFO]  plugin.terraform-provider-equinix_v1.1.0: 2021/04/13 12:57:05 [DEBUG] Equinix API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 Bad Request
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json;charset=UTF-8
Date: Tue, 13 Apr 2021 12:57:05 GMT
Server: istio-envoy
Set-Cookie: REDACTED
Set-Cookie: REDACTED
X-Application-Context: Equinix Fabric
X-Envoy-Upstream-Service-Time: 352

c9
[
 {
  "errorCode": "IC-LAYER2-AUTH-0015",
  "errorMessage": "Secondary Authorization Key cannot be empty",
  "moreInfo": "",
  "errorMessageKey": "IC-LAYER2.IC-LAYER2-AUTH-0015",
  "property": "secondaryAuthorizationKey"
 }
]
0
```

Notes:

* Where it says <redacted-hash> there are hashes and the value is not empty. (Actually, I think those are UUIDs)
* I removed the value for Set-Cookie in the response block out of ignorance and caution, I think I shouldn't paste it, please correct me if I'm wrong.
* `test-conn-pri` and `test-conn-sec` are made up names following the report example.

**Comment by mikouaj** [comment] 2021-04-13 15:03
@mxdlx thanks for providing debug log data.
We learned from it that Terraform provider is correctly populating `secondaryAuthorizationKey` in API request body,
The issue seems to be API call structure or Equinix Fabric related then.

Can you check one more thing: 
1. Add `profile_uuid` to `secondary_connection` block in your Terraform connection config - same value can be used as for primary
2. Try `terraform apply` again

**Comment by mxdlx** [comment] 2021-04-13 15:20
It failed again, just for testing I used a different Interconnect Zone for primary and secondary (it was the same in the initial report). Terraform resource:

```
resource "equinix_ecx_l2_connection" "test_conn_pri" {
  name              = "test-conn-pri"
  profile_uuid      = data.equinix_ecx_l2_sellerprofile.zone1_profile.uuid
  speed             = 10000
  speed_unit        = "MB"
  notifications     = ["REDACTED"]
  port_uuid         = data.equinix_ecx_port.primary_port.uuid
  vlan_stag         = 300
  seller_region     = "us-east4"
  seller_metro_code = "NY"
  authorization_key = google_compute_interconnect_attachment.vlan_attach_1.pairing_key

  secondary_connection {
    name              = "test-conn-sec"
    # profile_uuid provided for testing in
    # https://github.com/equinix/terraform-provider-equinix/issues/47
    profile_uuid      = data.equinix_ecx_l2_sellerprofile.zone2_profile.uuid
    speed             = 10000
    speed_unit        = "MB"
    port_uuid         = data.equinix_ecx_port.secondary_port.uuid
    vlan_stag         = 400
    seller_region     = "us-east4"
    seller_metro_code = "NY"
    authorization_key = google_compute_interconnect_attachment.vlan_attach_2.pairing_key
  }
}
```

And the trace:

Request:

```
2021-04-13T15:12:35.416Z [INFO]  plugin.terraform-provider-equinix_v1.1.0: 2021/04/13 15:12:35 [DEBUG] Equinix API Request Details:
---[ REQUEST ]---------------------------------------
POST /ecx/v3/l2/connections HTTP/1.1
Host: api.equinix.com
User-Agent: equinix/ecx-go
Content-Length: 770
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

{
 "primaryName": "test-conn-pri",
 "profileUUID": "bd4570e2-d792-4a00-87f5-3bde040cdcd7",
 "speed": 10000,
 "speedUnit": "MB",
 "notifications": [
  "REDACTED"
 ],
 "purchaseOrderNumber": null,
 "primaryPortUUID": "REDACTED",
 "primaryVlanSTag": 300,
 "secondaryName": "test-conn-sec",
 "secondaryPortUUID": "REDACTED",
 "secondaryVlanSTag": 400,
 "secondarySpeed": 10000,
 "secondarySpeedUnit": "MB",
 "secondaryProfileUUID": "b97dacca-abe6-4e8c-8be1-fcdd1be1defe",
 "secondaryAuthorizationKey": "<redacted-hash>/us-east4/2",
 "secondarySellerMetroCode": "NY",
 "secondarySellerRegion": "us-east4",
 "sellerRegion": "us-east4",
 "sellerMetroCode": "NY",
 "authorizationKey": "<redacted-hash>/us-east4/1"
}
```

Response:

```
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 Bad Request
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json;charset=UTF-8
Date: Tue, 13 Apr 2021 15:12:36 GMT
Server: istio-envoy
Set-Cookie: REDACTED
Set-Cookie: REDACTED
X-Application-Context: Equinix Fabric
X-Envoy-Upstream-Service-Time: 403

c9
[
 {
  "errorCode": "IC-LAYER2-AUTH-0015",
  "errorMessage": "Secondary Authorization Key cannot be empty",
  "moreInfo": "",
  "errorMessageKey": "IC-LAYER2.IC-LAYER2-AUTH-0015",
  "property": "secondaryAuthorizationKey"
 }
]
0
```

**Comment by chrisbnorman** [comment] 2021-09-08 17:40
did anyone manage to work this out, im having the same problem

**Comment by mxdlx** [comment] 2021-09-08 17:49
@chrisbnorman I ended up using the UI but I know there are newer versions of the provider.

**Comment by chrisbnorman** [comment] 2021-09-08 23:04
thanks @mxdlx I'm using the latest version of the provider 1.2 and still getting the same problem. not sure if its related but I'm connecting to google cloud.

**Comment by chrisbnorman** [comment] 2021-09-08 23:19
@mikouaj your working example looks to be using a device instead of a port. would that be handled any differently?

**Comment by nfwolfpryde** [comment] 2021-10-14 00:50
Okay, I have mine working now. It looks like the issue is the "Authorization Key" isn't used anymore, and the "service key" should be instead.

`-azurerm_express_route_circuit_authorization.demo.authorization_key
+azurerm_express_route_circuit.demo.service_key`

**Comment by ocobleseqx** [comment] 2022-03-02 15:46
HI @mxdlx, I'm not sure how it was working when this issue was raised but Redundant connections is not allowed to GCP service profile with a single resource or API request, and it doesn't matter if the origin of the connection is a Port or a Network Edge device. You can check also that from the portal, there you will need to select first the profile for the Google zone in depends on your Authorization key end (/1 or /2) and then you will be able to select just a single port/device/servicetoken. So, if you want to create a redundant connection you will need to define an equinix_ecx_l2_connection resource for each connection.

We are in process of creating a terraform module for each main cloud service 
provider so you will find easier to define that redundant connection to google cloud or other service providers. https://github.com/equinix/terraform-provider-equinix/issues/100

I'm going to close this issue, but feel free to reopen it if you still have related issues.

**Comment by ocobleseqx** [comment] 2022-03-02 15:54
@nfwolfpryde we updated the connectivity example to Azure to address what you mentioned. It was included in v.1.4.0 https://github.com/equinix/terraform-provider-equinix/pull/71

**Closed by ocobleseqx** 2022-03-02 15:54 UTC
