### ISSUE TITLE
Update tests/docs/etc. to account for decommissioned data centers

### ISSUE THREAD

**Issue by ctreatma** [equinix/terraform-provider-equinix#281] opened 2022-12-01 19:39 UTC
A few data centers are no longer supported.  We have at least a couple acceptance tests that are using these data centers, which causes those tests to fail.  We may also be referencing those data centers in examples or guides.  Update any tests/examples/guides to replace references to unsupported data centers as follows:

- NRT1 => TY
- AMS1 => AM
- SJC1 => SV
- DFW2 => DA
- EWR1 => NY

**Comment by displague** [comment] 2023-05-31 16:20
Dupe of #130

**Closed by displague** 2023-05-31 16:20 UTC
